# Generated by Django 5.1.4 on 2025-06-04 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.CharField(blank=True, default='https://drivemate-1.onrender.com/media/dp.jpg', max_length=255),
        ),
    ]
