# Generated by Django 5.1.4 on 2025-05-14 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('category', models.CharField(choices=[('sedan', 'Sedan'), ('SUV', 'SUV'), ('Station Wagon', 'Station Wagon')], max_length=15)),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel')], default='Petrol', max_length=10)),
                ('mileage', models.IntegerField()),
                ('transmission', models.CharField(choices=[('automatic', 'automatic'), ('manual', 'manual')], default='automatic', max_length=15)),
                ('status', models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('maintenance', 'Maintenance')], default='available', max_length=15)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dynamic_daily_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('breakdown_risk', models.CharField(choices=[('Low', 'Low'), ('High', 'High'), ('Moderate', 'Moderate')], default='Low', max_length=15)),
                ('total_rental_duration', models.IntegerField(default=0)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('image_url', models.TextField()),
                ('is_german', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_detected', models.CharField(max_length=100)),
                ('detected_on', models.DateField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
            ],
        ),
    ]
